// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'Current platform is not supported for Firebase.',
        );
    }
  }

  // --------------------------
  // WEB
  // --------------------------
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIPRNRPgKpt9adtoJSnrKXQbvMTN4FmhU',
    appId: '1:124583801317:web:20b84ef3955f55581c3f0c',
    messagingSenderId: '124583801317',
    projectId: 'bitirmeprojesi-9b244',
    authDomain: 'bitirmeprojesi-9b244.firebaseapp.com',
    storageBucket: 'bitirmeprojesi-9b244.firebasestorage.app',
  );

  // --------------------------
  // ANDROID (DÜZGÜN HALİ)
  // --------------------------
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZyrzaP111ey_oghi-pSEBTv1vx7pyrtw',
    appId: '1:124583801317:android:d8892a9b6832f3da1c3f0c',
    messagingSenderId: '124583801317',
    projectId: 'bitirmeprojesi-9b244',
    storageBucket: 'bitirmeprojesi-9b244.firebasestorage.app',
  );

  // --------------------------
  // iOS
  // --------------------------
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs0bLD7mdbUo75cnPSYjexjozHrGZVV7A',
    appId: '1:124583801317:ios:0c6fa797e147aa6e1c3f0c',
    messagingSenderId: '124583801317',
    projectId: 'bitirmeprojesi-9b244',
    storageBucket: 'bitirmeprojesi-9b244.firebasestorage.app',
    iosBundleId: 'com.example.avatar2',
  );

  // --------------------------
  // macOS
  // --------------------------
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBs0bLD7mdbUo75cnPSYjexjozHrGZVV7A',
    appId: '1:124583801317:ios:0c6fa797e147aa6e1c3f0c',
    messagingSenderId: '124583801317',
    projectId: 'bitirmeprojesi-9b244',
    storageBucket: 'bitirmeprojesi-9b244.firebasestorage.app',
    iosBundleId: 'com.example.avatar2',
  );

  // --------------------------
  // WINDOWS
  // --------------------------
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIPRNRPgKpt9adtoJSnrKXQbvMTN4FmhU',
    appId: '1:124583801317:web:485e4db252262e4f1c3f0c',
    messagingSenderId: '124583801317',
    projectId: 'bitirmeprojesi-9b244',
    authDomain: 'bitirmeprojesi-9b244.firebaseapp.com',
    storageBucket: 'bitirmeprojesi-9b244.firebasestorage.app',
  );
}
